const { Hand, Action } = require("./enums.js");

/* prettier-ignore */
const Instrument = {
  WheatstoneCG30: {
    title: "CG Wheatstone 30",
    layout: [
      { [Action.PUSH]: "E3", [Action.PULL]: "F3", hand: Hand.LEFT, cooverLabel: "1a" },
      { [Action.PUSH]: "A3", [Action.PULL]: "Bb3",hand: Hand.LEFT, cooverLabel: "2a" },
      { [Action.PUSH]: "C#4",[Action.PULL]: "D#4",hand: Hand.LEFT, cooverLabel: "3a" },
      { [Action.PUSH]: "A4", [Action.PULL]: "G4", hand: Hand.LEFT, cooverLabel: "4a" },
      { [Action.PUSH]: "G#4",[Action.PULL]: "Bb4",hand: Hand.LEFT, cooverLabel: "5a" },
      { [Action.PUSH]: "C#5",[Action.PULL]: "D#5",hand: Hand.RIGHT,cooverLabel: "1a" },
      { [Action.PUSH]: "A5", [Action.PULL]: "G5", hand: Hand.RIGHT,cooverLabel: "2a" },
      { [Action.PUSH]: "G#5",[Action.PULL]: "Bb5",hand: Hand.RIGHT,cooverLabel: "3a" },
      { [Action.PUSH]: "C#6",[Action.PULL]: "D#6",hand: Hand.RIGHT,cooverLabel: "4a" },
      { [Action.PUSH]: "A6", [Action.PULL]: "F6", hand: Hand.RIGHT,cooverLabel: "5a" },
      { [Action.PUSH]: "C3", [Action.PULL]: "G3", hand: Hand.LEFT, cooverLabel: "1" },
      { [Action.PUSH]: "G3", [Action.PULL]: "B3", hand: Hand.LEFT, cooverLabel: "2" },
      { [Action.PUSH]: "C4", [Action.PULL]: "D4", hand: Hand.LEFT, cooverLabel: "3" },
      { [Action.PUSH]: "E4", [Action.PULL]: "F4", hand: Hand.LEFT, cooverLabel: "4" },
      { [Action.PUSH]: "G4", [Action.PULL]: "A4", hand: Hand.LEFT, cooverLabel: "5" },
      { [Action.PUSH]: "C5", [Action.PULL]: "B4", hand: Hand.RIGHT,cooverLabel: "1" },
      { [Action.PUSH]: "E5", [Action.PULL]: "D5", hand: Hand.RIGHT,cooverLabel: "2" },
      { [Action.PUSH]: "G5", [Action.PULL]: "F5", hand: Hand.RIGHT,cooverLabel: "3" },
      { [Action.PUSH]: "C6", [Action.PULL]: "A5", hand: Hand.RIGHT,cooverLabel: "4" },
      { [Action.PUSH]: "E6", [Action.PULL]: "B5", hand: Hand.RIGHT,cooverLabel: "5" },
      { [Action.PUSH]: "B3", [Action.PULL]: "A3", hand: Hand.LEFT, cooverLabel: "6" },
      { [Action.PUSH]: "D4", [Action.PULL]: "F#4",hand: Hand.LEFT, cooverLabel: "7" },
      { [Action.PUSH]: "G4", [Action.PULL]: "A4", hand: Hand.LEFT, cooverLabel: "8" },
      { [Action.PUSH]: "B4", [Action.PULL]: "C5", hand: Hand.LEFT, cooverLabel: "9" },
      { [Action.PUSH]: "D5", [Action.PULL]: "E5", hand: Hand.LEFT, cooverLabel: "10" },
      { [Action.PUSH]: "G5", [Action.PULL]: "F#5",hand: Hand.RIGHT,cooverLabel: "6" },
      { [Action.PUSH]: "B5", [Action.PULL]: "A5", hand: Hand.RIGHT,cooverLabel: "7" },
      { [Action.PUSH]: "D6", [Action.PULL]: "C6", hand: Hand.RIGHT,cooverLabel: "8" },
      { [Action.PUSH]: "G6", [Action.PULL]: "E6", hand: Hand.RIGHT,cooverLabel: "9" },
      { [Action.PUSH]: "B6", [Action.PULL]: "F#6",hand: Hand.RIGHT,cooverLabel: "10" },
    ],
  },
  JeffriesCG30: {
    title: "CG Jeffries 30",
    layout: [
      { [Action.PUSH]: "E3", [Action.PULL]: "F3", hand: Hand.LEFT, cooverLabel: "1a" },
      { [Action.PUSH]: "A3", [Action.PULL]: "Bb3",hand: Hand.LEFT, cooverLabel: "2a" },
      { [Action.PUSH]: "C#4",[Action.PULL]: "D#4",hand: Hand.LEFT, cooverLabel: "3a" },
      { [Action.PUSH]: "A4", [Action.PULL]: "G4", hand: Hand.LEFT, cooverLabel: "4a" },
      { [Action.PUSH]: "G#4",[Action.PULL]: "Bb4",hand: Hand.LEFT, cooverLabel: "5a" },
      { [Action.PUSH]: "D#5",[Action.PULL]: "C#5",hand: Hand.RIGHT,cooverLabel: "1a" },
      { [Action.PUSH]: "C#5",[Action.PULL]: "D#5",hand: Hand.RIGHT,cooverLabel: "2a" },
      { [Action.PUSH]: "G#5",[Action.PULL]: "G5", hand: Hand.RIGHT,cooverLabel: "3a" },
      { [Action.PUSH]: "C#6",[Action.PULL]: "Bb5",hand: Hand.RIGHT,cooverLabel: "4a" },
      { [Action.PUSH]: "A5", [Action.PULL]: "D6", hand: Hand.RIGHT,cooverLabel: "5a" },
      { [Action.PUSH]: "C3", [Action.PULL]: "G3", hand: Hand.LEFT, cooverLabel: "1" },
      { [Action.PUSH]: "G3", [Action.PULL]: "B3", hand: Hand.LEFT, cooverLabel: "2" },
      { [Action.PUSH]: "C4", [Action.PULL]: "D4", hand: Hand.LEFT, cooverLabel: "3" },
      { [Action.PUSH]: "E4", [Action.PULL]: "F4", hand: Hand.LEFT, cooverLabel: "4" },
      { [Action.PUSH]: "G4", [Action.PULL]: "A4", hand: Hand.LEFT, cooverLabel: "5" },
      { [Action.PUSH]: "C5", [Action.PULL]: "B4", hand: Hand.RIGHT,cooverLabel: "1" },
      { [Action.PUSH]: "E5", [Action.PULL]: "D5", hand: Hand.RIGHT,cooverLabel: "2" },
      { [Action.PUSH]: "G5", [Action.PULL]: "F5", hand: Hand.RIGHT,cooverLabel: "3" },
      { [Action.PUSH]: "C6", [Action.PULL]: "A5", hand: Hand.RIGHT,cooverLabel: "4" },
      { [Action.PUSH]: "E6", [Action.PULL]: "B5", hand: Hand.RIGHT,cooverLabel: "5" },
      { [Action.PUSH]: "B3", [Action.PULL]: "A3", hand: Hand.LEFT, cooverLabel: "6" },
      { [Action.PUSH]: "D4", [Action.PULL]: "F#4",hand: Hand.LEFT, cooverLabel: "7" },
      { [Action.PUSH]: "G4", [Action.PULL]: "A4", hand: Hand.LEFT, cooverLabel: "8" },
      { [Action.PUSH]: "B4", [Action.PULL]: "C5", hand: Hand.LEFT, cooverLabel: "9" },
      { [Action.PUSH]: "D5", [Action.PULL]: "E5", hand: Hand.LEFT, cooverLabel: "10" },
      { [Action.PUSH]: "G5", [Action.PULL]: "F#5",hand: Hand.RIGHT,cooverLabel: "6" },
      { [Action.PUSH]: "B5", [Action.PULL]: "A5", hand: Hand.RIGHT,cooverLabel: "7" },
      { [Action.PUSH]: "D6", [Action.PULL]: "C6", hand: Hand.RIGHT,cooverLabel: "8" },
      { [Action.PUSH]: "G6", [Action.PULL]: "E6", hand: Hand.RIGHT,cooverLabel: "9" },
      { [Action.PUSH]: "B6", [Action.PULL]: "F#6",hand: Hand.RIGHT,cooverLabel: "10" },
    ],
  },
};

module.exports = {
  Instrument,
};
